---
output:
  pdf_document:
    latex_engine: xelatex
    keep_tex: false
geometry:
- paperwidth=8.5in
- paperheight=11in
- margin=0.05in
header-includes:
  \usepackage{fontspec}
  \setmainfont{Calibri}
  \usepackage{booktabs}
  \usepackage{colortbl}
  \usepackage{subfig}
  \usepackage{floatrow}
  \usepackage{sectsty}
  \usepackage{titlesec}
  \graphicspath{{C:/Users/tdmed/OneDrive/_Github/boomers-analytics/www}}
---
```{r setup, include=FALSE}
library(ggplot2)
library(GeomMLBStadiums)
library(ggnewscale)
library(cowplot)
library(tidyverse)
library(stringr)
library(RSQLite)
library(grid)
library(gridExtra)
library(cowplot)
library(glue)

# opts_chunk$set(echo = FALSE)
# knitr::opts_chunk$set(fig.pos = '!h')
```
\newpage
\begin{center}
\textbf{\normalsize Infield Charts}
\end{center}

```{r infield, echo = F, warning = F, fig.width=6.75, fig.height=10}
cowplot::plot_grid(plot_if, plot_if, plot_if, plot_if, nrow = 2, ncol = 2)

```



\newpage
\begin{center}
\textbf{\normalsize Ouftield Charts}
\end{center}
```{r outfield, echo = F, warning = F, fig.width=6.75, fig.height=10.1}
cowplot::plot_grid(plot_with_legend, plot_with_legend,plot_with_legend, plot_with_legend,  nrow = 2, ncol = 2)


```



\newpage
\begin{center}
\textbf{\normalsize For Coaches}
\end{center}
```{r coaches, echo = F, warning = F, fig.width=6.75, fig.height=10.1}
# \newpage
cowplot::plot_grid(plot_if, plot_with_legend, plot_if, plot_with_legend, nrow = 2, ncol = 2)
```